
language: node_js
node_js:
  - 14.8.0

cache: 
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn run build
  - yarn run build:tailwind
  - yarn run test:all

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
